# fly.toml app configuration file generated for find-class-room-backend-late-lake-107-damp-glade-3955 on 2024-01-14T17:32:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "find-class-room-backend-late-lake-107-damp-glade-3955"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
