name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  merge:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: lint_and_test
    if: github.event_name == 'merge' && github.branch == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to production
        run: |
          # Add your deployment script or command here
          echo "Deploying to production"
